#Updated Dynamic Properties
#Fri May 02 13:43:31 AEST 2025
captchaAlert=
contactUsSuccessMessage=
contactUsUrl=
demoShopUrl=
eJunkieUrl=
email=
expectedBookPrice=
explicitWait=
invalidCardExpDate=
invalidCreditCardNum=
invalidCvc=
message=
name=
pageLoadTimeout=
promoCode=
subject=
successMessage=
validCardExpDate=
validCreditCardNum=
validCvc=
