demoShopUrl=
pageLoadTimeout=
explicitWait=
captchaWait=
promoCode=
name=
email=
invalidCreditCardNum=
invalidCardExpDate=
invalidCvc=
validCreditCardNum=
validCardExpDate=
validCvc=
subject=
message=
contactUsUrl=
eJunkieUrl=
captchaAlert=
contactUsSuccessMessage=
